### ISSUE TITLE
As a user, I want to look through archives of blog posts

### ISSUE THREAD

**Issue by li-kai** [nushackers/nushackers-site#52] opened 2017-06-27 06:32 UTC
Three separations - year, year/month & year/month/day
- [ ] nushackers.org/2017
- [ ] nushackers.org/2017/01
- [ ] nushackers.org/2017/01/01

**Comment by unusep** [comment] 2017-07-19 08:41
hugo does not natively support archiving at the moment (Issue 448`https://github.com/gohugoio/hugo/issues/448`), so my current plan is to work around this by generating the archive pages in `nushackers-site/_scripts/gen_fh.py`

**Comment by jethrokuan** [comment] 2017-07-19 08:53
I don't see anyone going to these links though

**Comment by li-kai** [comment] 2017-07-22 08:58
I think discovery of these links aren't obvious.

@unusep I think hugo's filtering and grouping syntax is pretty powerful, could you do something like [this](https://github.com/RickCogley/RCC-Hugo2015/blob/58f15ec7820307ee9c0a843a1abd30097de08567/layouts/_default/section.html)

**Comment by unusep** [comment] 2017-07-25 08:53
@li-kai The problem is that (I think) Hugo does not automatically generate a daily/monthly/yearly archive page. We'll have to manually create one for each post. It's probably cleanest to do that by leveraging off the script that we (plan to?) run here: 
```About writing posts: https://gohugo.io/content/

If you are write those generic posts about Friday hacks, please run:

npm run friday-hacks <Title> <Your name>```

**Comment by unusep** [comment] 2017-08-02 16:41
do we still want to do breakdowns by year, year/month and year/month/day? we can close this issue otherwise.

**Comment by advaypal** [comment] 2017-08-02 16:53
I think this isn't necessary for now, especially if we do (#55)

**Closed** 2017-08-02 17:00 UTC
